name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
      # Note: This is disabled because it was causing issues with installation of the example application
      # - name: Use Node Modules Cache
      #   uses: actions/cache@v2
      #   with:
      #     path: "**/node_modules"
      #     key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies for Vite Plugin Relay
        run: yarn install --frozen-lockfile
      - name: Install Playwright
        run: npx playwright@1.17.1 install --with-deps
      - name: Build Vite Plugin Relay
        run: yarn build
      - name: Install Dependencies for Vite 3 Example Site
        run: yarn --cwd ./examples/vite-3 install --frozen-lockfile
      - name: Test Vite 3 Example Site
        run: yarn --cwd ./examples/vite-3 test
      - name: Install Dependencies for Vite 2 Example Site
        run: yarn --cwd ./examples/vite-2 install --frozen-lockfile
      - name: Test Vite 2 Example Site
        run: yarn --cwd ./examples/vite-2 test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Use Node Modules Cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies for Vite Plugin Relay
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
